### ISSUE TITLE
Bootstrap failure

### ISSUE THREAD

**Issue by rhdtownsend** [iains/gcc-13-branch#18]
I'm trying to build 13.2 on MacOS 14.4.1. I applied the patch at 

https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=9970b576b7e4ae337af1268395ff221348c4b34a

...but run into the following bootstrap failure:

> rm -f stage_current
> Comparing stages 2 and 3
> Bootstrap comparison failure!
> aarch64-apple-darwin20/libstdc++-v3/src/.libs/libstdc++.6.dylib-master.o differs
> make[2]: *** [compare] Error 1
> make[1]: *** [stage3-bubble] Error 2
> make: *** [all] Error 2
> FAILED in make for gcc
> Action install failed for package gcc/gcc-13.2-darwin
> 

This is with CLT 15.3, and configuring with the following:

 /opt/sdk2-tmp/build/gcc/configure CC=clang CXX=clang++ --build=aarch64-apple-darwin20 --host=aarch64-apple-darwin20 --target=aarch64-apple-darwin20 --prefix=/opt/sdk2-tmp/mesasdk --with-gmp=/opt/sdk2-tmp/mesasdk --with-mpfr=/opt/sdk2-tmp/mesasdk --with-mpc=/opt/sdk2-tmp/mesasdk --enable-languages=c,c++,fortran --disable-multilib --disable-nls --disable-libsanitizer --with-sysroot=/opt/sdk2-tmp/mesasdk/sysroot --without-build-config

**Comment by iains** [comment]
there are a number of issues with changes in the macOS 14 and CLT.

I believe they are solved in the current 13.3 pre-release branch (https://github.com/iains/gcc-13-branch/tree/gcc-13-3-darwin-pre-0) if you would like to try that [noting that it will be force-pushed / rebased and mostly unsupported until it becomes the 13-3-darwin branch].  I suspect that, because 13.3 is likely not far in the future (june or so) it will not be considered worth trying to do another 13.2 release.

**Comment by rhdtownsend** [comment]
I've just tried the pre-release branch, and I still get the same error. However, the errors go away (on pre-release and on patched 13.2) if I remove the --without-build-config flag (which I started adding a few releases ago, to work around a different issue). So, probably a false alarm on my part.

**Comment by iains** [comment]
> I've just tried the pre-release branch, and I still get the same error. However, the errors go away (on pre-release and on patched 13.2) if I remove the --without-build-config flag (which I started adding a few releases ago, to work around a different issue). So, probably a false alarm on my part.

Aha ... you reminded me I was intending to ask why that was there - it's a odd one; I will have to see what is expected to happen there.  My general rule of thumb is "don't add configure options unless there's a clear reason and an explanation of the effect of the change" .. there are simply too many to test (yet another combinatorial test matrix explosion)

**Comment by iains** [comment]
note: that there _are_ still issues with the 13.2 release + macOS14 + CLT15 (many test fails because of increased linker diagnostics, for one).

**Comment by iains** [comment]
Those should be fixed with the  13.3 release when it comes and the 14.1 branch which should be released during May.

**Comment by iains** [comment]
fixed in 13.3-darwin-r0
